version: '3.3'

services:
  db:
    image: mariadb
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: xrnl
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: pass
    networks:
      - xrnl

  php:
    build: .
    depends_on:
      - db
    volumes:
      - .:/var/www/html
      - ./vhost.conf:/etc/apache2/sites-available/000-default.conf
    working_dir: /var/www/html
    ports:
      - 8000:80
    networks:
      - xrnl

volumes:
    db_data: {}

networks:
  xrnl:
