version: "3.3"

services:
  db:
    image: mariadb
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306
    restart: always
    command: "mysqld --innodb-flush-method=fsync"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: xrnl
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: pass
    networks:
      - xrnl

  php:
    build: .
    depends_on:
      - db
      - composer
    volumes:
      - .:/var/www/html
      - ./vhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 8000:80
    networks:
      - xrnl

  composer:
    image: composer
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: install

  # Database query browser
  metabase:
    image: metabase/metabase
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./metabase_data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db

volumes:
  db_data: {}
  metabase_data: {}

networks:
  xrnl:
