version: "3.3"

services:
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306
    restart: always
    command: "mysqld --innodb-flush-method=fsync"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: xrnl
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: pass
    networks:
      - xrnl

  php:
    image: extinctionrebellion/website:dev
    depends_on:
      - db
      - composer
    volumes:
      - plugins:/var/www/html
      - vhost:/etc/apache2/sites-available/
    ports:
      - 8000:80
    networks:
      - xrnl

  composer:
    image: extinctionrebellion/composer:dev
    working_dir: /var/www/html
    volumes:
      - plugins:/var/www/html
    command: install

volumes:
  db_data: {}
  vhost:
  plugins:

networks:
  xrnl:
